// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SpesenApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250717174505_FixedPersonName")]
    partial class FixedPersonName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("SpesenApp.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nachname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Personen");
                });

            modelBuilder.Entity("SpesenApp.Models.SpesenEintrag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AndereKosten")
                        .HasColumnType("TEXT");

                    b.Property<string>("Beschreibung")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("KmAuto")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kst1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kst2")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Kursmaterial")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PersonenId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Reisekosten")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ReisespesenAuto")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Verpflegung")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("SpesenEintraege");
                });

            modelBuilder.Entity("SpesenApp.Models.SpesenEintrag", b =>
                {
                    b.HasOne("SpesenApp.Models.Person", "Person")
                        .WithMany("Spesen")
                        .HasForeignKey("PersonId");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("SpesenApp.Models.Person", b =>
                {
                    b.Navigation("Spesen");
                });
#pragma warning restore 612, 618
        }
    }
}
